version: '3.8'

services:
  backend:
    build:
      context: ./backend/DataSpecificationNavigatorBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Map the host ./backend_data to /app/data in the container.
      # That's where the SQLITE file is.
      - ./backend_data:/app/data

  frontend:
    build:
      context: ./frontend/DataSpecificationNavigatorFrontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend # Not really, but it's meaningless to run the frontend without backend.

