services:
  backend:
    build:
      context: ./backend/DataSpecificationNavigatorBackend
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      # Map the host ./backend_data to /app/data in the container.
      # That's where the SQLITE file is.
      - ./backend_data:/app/data
    extra_hosts:
      # Apparently, on Linux, the host.docker.internal is not automatically mapped.
      # So map it to the host IP address here.
      - "host.docker.internal:host-gateway"
    environment:
      - "Env:Llm:Ollama:Uri=${OLLAMA_URI}"
      - "Env:Llm:Ollama:Model=${OLLAMA_MODEL}"
      - "Env:Llm:Ollama:RetryAttempts=${RETRY_ATTEMPTS}"
      - "Env:Dataspecer:Url=${DATASPECER_URL}"

  frontend:
    build:
      context: ./frontend/DataSpecificationNavigatorFrontend
      dockerfile: Dockerfile
      args:
      - BASE_URL=${BASE_URL:-/}
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - VITE_BASE_URL=${BASE_URL:-/}
    depends_on:
      - backend # Not really, but it's meaningless to run the frontend without backend.
